ssciwr/iwr-interactive-visualization

docs/script.js, docs/style.css
- to reset selection
- click on background
- click on currently selected segment
- make cursor a pointer over segments to indicate that they are clickable
- resolves #1
=> click on segment instead of mouse hover to activate

docs/script.js
- don't do this if a segment is currently selected
- resolves #4
=> also display groups on hover over segment

docs/script.js
=> wider stroke to outline selected segment

docs/script.js
=> add transitions to opacity and border outline

docs/script.js
- instead of on/off, transparency of group is weighted similar to outer segments
- resolves #14
- construct group weights by tranposing application/method weights
- resolves 13
=> set group transparency according to weight

docs/script.js
- make each group box a link to the group webpage
- professor name above, group name below, both centered
- remove border & drop-shadow from groups
=> add professor name & link to group website

docs/script.js
- group input data together at top
- use single color for groups, methods, applications
=> refactor code

docs/style.css
- listed in order of preference
- resolves #22
=> specify font-family in css

docs/script.js
=> Content research groups

docs/script.js
- reduce font size & padding
- split longer group names into multiple lines
- (use "\n" instead of a space to add a line break)
also
- fix commas used instead of decimal point in weights
- use mouseenter/mouseleave instead of mouseover/mouseout
- doesn't trigger when entering/leaving children
=> fix missing / oddly-shaped groups

docs/script.js
- round edges of group rectangle
- if there are more than 6 rows, also reduce the size of each group
=> center groups in circle

docs/index.html, docs/script.js
- animate size & location changes of group boxes
=> animate group transitions

docs/script.js, docs/style.css
- use more space, allows boxes to be larger
- locations in grid are hard-coded for now
=> re-arrange group boxes

docs/script.js
- move shorter names closer to centre
- make font bold
- also: add gradient as background
- resolves #39
=> adjust vertical line spacing of groups text

docs/script.js
- invert colours of text/bg
- resolves #33
segment text goes blue on mouseover to suggest it is clickable
- resolves #34
- also resolves #35, resolves #37
=> add curved arrows to segment labels

docs/script.js
- instead of hard-coded grid when all groups are displayed
- automatic 4-col layout with 2/3 rows of 2 top/bottom, group box height determined from required number of columns
- resolves #42
=> make group layout automatic

docs/script.js
=> maintain segment highlights when card is displayed

docs/script.js, docs/style.css
- square corners
- white background
- no border
- drop shadow
- resolves #69
=> change group box/card styling

docs/script.js
- group name
- photo
- prof name
- blurb
- resolves #70
=> change group card layout

docs/script.js
- small for 4 column view
- large for 2/3 column view
- resolves #67
=> only have two group box sizes

docs/script.js
- hover
- text goes white instead of blue
- arc is also outlined in thin white border
- looks more like a button to be clicked
- clicked
- text remains white & border remains until de-selected
=> change segment hover/click styling

docs/script.js
- replace first/middle names with initial and point
- keep full name in group card
- resolves #46
=> shorten prof names in group boxes

docs/script.js
- add `show_groups=false` boolean to script to toggle showing them
- resolves #82
=> remove groups from boxes

src/js/script.ts
- consistent spacing between bottom of group name & subsequent elements
- resolves #97
=> adjust vertical spacing of group box

src/css/style.css, src/js/script.ts
- clicking on close button or background around the card closes card
- clicking on inside of card no longer closes card
- resolves #66
=> add close button to group cards

src/css/style.css, src/js/script.ts
- mouse changes to pointer on clickable elements
- reduce width of all line strokes
=> improve settings button

scripts/build.mjs, src/data/data.json, src/js/script.ts, src/js/utils.ts
- replace src/js/data.ts with src/data/data.json
- re-organise data to make it easier to edit
- json is loaded from relative url "fileadmin/iwr_vis/data.json"
- "colour" -> "color" in JSON & code for consistency with css
- add image_base_url
- use image filenames from json instead of auto-constructing from prof name
- put data.json and images in fileadmin/iwr_vis subfolder to suit existing IWR website folder structure
- resolves #105
=> read data as json from url on pageload

README.md, package-lock.json, package.json
- builds website from source
- starts a local http-server serving `/dist`
- opens this in a web browser
=> add `npm run preview` command

.pre-commit-config.yaml, src/js/script.ts
=> make prof image a link to website
